name: clickJobs
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.3.0"

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_screenutil: ^5.8.2
  loading_animation_widget: ^1.2.0+4
  intro_screen_onboarding_flutter: ^1.0.0
  flutter_overboard: ^3.1.1
  icons_plus: ^3.0.0
  animated_icon_button: ^1.0.2
  flutter_snake_navigationbar: ^0.6.1
  day_night_switcher: ^0.2.0+1
  proste_indexed_stack: ^0.2.4
  intl_phone_number_input: ^0.7.2
  flutter_svg: ^1.1.6
  sms_autofill: ^2.2.0
  flutter_advanced_drawer: ^1.3.3
  flutter_launcher_icons: ^0.11.0

  #back
  dio: ^4.0.6
  shared_preferences: ^2.0.17
  provider: ^6.0.5
  firebase_messaging: ^14.2.2
  firebase_core: ^2.4.1
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  intl: ^0.17.0
  csc_picker: ^0.2.7
  firebase_auth: ^4.4.0
  google_sign_in: ^6.1.0

flutter_icons:
  android:
    enable: true
  ios:
    enable: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
